import { StyleSheet } from "react-native";

export const GameLevelsStyle = StyleSheet.create({
  ContainerButtonHead: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
    width: "100%",
    marginTop: 50,
    marginBottom: 20,
    paddingRight: 20,
    gap: 20,
  },
  ContentTitle: {
    alignItems: "center",
  },
  scroll: {
    margin: 35,
    marginTop: 20,
  },
  Body: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  ContentImage: {
    maxWidth: 210,
    justifyContent: "flex-end",
    height: "100%",
  },
  Image: {
    width: 210,
    height: 560,
    marginBottom: 10,
  },
  ContentStar: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    marginBottom: 20,
    marginLeft: 20,
    height: "17%",
  },
  StarType1: {
    width: 0.8,
    height: 0.8,
    backgroundColor: "white",
    borderRadius: "50%",
    borderWidth: 0.8,
    borderColor: "white",
    shadowColor: "rgba(50,115,220, 0.9)",
    marginBottom: 70,
    marginRight: 50,
  },
  StarType2: {
    width: 1.3,
    height: 1.3,
    backgroundColor: "#E5E5E5",
    borderRadius: "50%",
    borderWidth: 1.3,
    borderColor: "#E5E5E5",
    shadowColor: "rgba(50,115,220, 0.9)",
    marginLeft: 30,
  },
  StarType3: {
    width: 0.8,
    height: 0.8,
    backgroundColor: "white",
    borderRadius: "50%",
    borderWidth: 0.8,
    borderColor: "white",
    shadowColor: "rgba(50,115,220, 0.9)",
    marginTop: 80,
    marginLeft: 30,
    marginRight: 50,
  },
  StarType4: {
    width: 1.3,
    height: 1.3,
    backgroundColor: "#E5E5E5",
    borderRadius: "50%",
    borderWidth: 1.3,
    borderColor: "#E5E5E5",
    shadowColor: "rgba(50,115,220, 0.9)",
    marginLeft: 30,
    marginTop: 25,
  },
  StarType5: {
    width: 0.8,
    height: 0.8,
    backgroundColor: "white",
    borderRadius: "50%",
    borderWidth: 0.8,
    borderColor: "white",
    shadowColor: "rgba(50,115,220, 0.9)",
    marginLeft: 70,
  },
  StarType6: {
    width: 0.8,
    height: 0.8,
    backgroundColor: "#E5E5E5",
    borderRadius: "50%",
    borderWidth: 0.8,
    borderColor: "#E5E5E5",
    shadowColor: "rgba(50,115,220, 0.9)",
  },
});
